version: "3.8"
services:
    fastapi:
        build: .
        ports:
            - 8000:8000
        volumes:
            - ./:/usr/src/app

        # env_file:
        #     - ./.env

        environment:
            - Database_Host=postgres 
            - Database_Port=5433
            - Database_Username=postgres
            - Database_Password=apple
            - Database_Name=test
            - secret_key=a6cb0906b9f6f457d2bec73def41bbcaf5081056ed61dfb6a0feb972f712387e3cf19b8aedbf0e8b241bc0e439f92a23
            - algorithm=HS256
            - access_token_expire_minutes=60

        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

        depends_on:
            - postgres

    postgres:
        image: postgres:15.4-alpine3.18
        expose:
            - 5433/tcp
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=apple
            - POSTGRES_DB=test
        volumes:
            - postgres-db:/var/lib/postgresql/data

        command: -p 5433

volumes:
    postgres-db:
